version: "3.8"

volumes:
  mongo_data:  # том для хранения данных MongoDB

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_lab4
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db  # сохраняем данные вне контейнера
    ports:
      - "27017:27017"  # проброс порта для Compass

  api:
    build: .  # собираем образ из Dockerfile в папке api
    container_name: express_lab4
    restart: unless-stopped
    ports:
      - "3000:3000"  # проброс порта для Node.js приложения
    environment:
      - MONGO_DB_HOSTNAME=mongodb  # имя сервиса MongoDB
      - MONGO_DB_PORT=27017
      - MONGO_DB=usersdb
    depends_on:
      - mongodb
